In [73]:
#new ipython notebook to calculate position and orientation for config file!!
#phi positive is moving to the right
# Roh 2012: hand positioned at 60% of arm length from shoulder

import numpy as np
from numpy import cos, sin, tan
from amcmorl_py_tools.vecgeom import transformations

#transformation matrix Rz, base offset -45 degrees
a=np.radians(-45)
Rzz = np.array([[cos(a), -sin(a), 0], [sin(a), cos(a), 0], [0,0,1]])

home = [0.500, -0.500, 0.300, 1.7560, -0.7290, 1.7560]#start position and orientation

arm = 0.60
shoulder = home[0:3]+np.dot(Rzz,np.array([0.6*arm+0.16,0,0]))
th = np.radians(15)
phi = np.radians(0) #negative is robot direction to left
#to left phi 15 degrees kan nog net!!
#of voor alle metingen de base veranderen?
th2 = np.radians(90) - th
th3 = np.radians(90) + th
sphere_pos = np.array([-(arm+0.16) * sin(th2) * cos(phi), (arm+0.16) * sin(th2) * sin(phi), (arm+0.16) * cos(th2)])

begin = transformations.Rz(np.radians(90)) #turn 90 z-axis, y-axis of transducer upwards

turn_theta = np.dot(transformations.Rx(th3),begin)
turn_phi = np.dot(transformations.Rz(-phi-a),turn_theta) # "a" is base-offset

orientation = transformations.DCM2axang(turn_phi)

#orientation = np.array([th3 * cos(-a - phi), th3 * sin(-a - phi), 0])
target = np.hstack([np.dot(Rzz, sphere_pos) + shoulder, orientation])
print target

[ 0.34860587 -0.34860587  0.49670247  2.01339487 -0.83397546  1.54493222]


In [35]:
begin = np.dot(transformations.Rx(np.radians(90)),transformations.Rz(np.radians(90)),transformations.Rz(np.radians(45))) 

In [40]:
print home

[0.5, -0.5, 0.3, 1.756, -0.729, 1.756]


In [15]:
np.radians(90+10)*cos(-np.radians(-45)+np.radians(-45))

1.7453292519943295

In [16]:
sin((np.radians(45)+np.radians(-45)))

0.0

In [77]:
np.dot(transformations.Rz(np.radians(0)),(target[:3]-home[:3]))

array([-0.15139413,  0.15139413,  0.19670247])

In [13]:
home

[0.5, -0.5, 0.3, 1.756, -0.729, 1.756]

In [14]:
target

array([ 0.33029437, -0.33029437,  0.3       ,  1.7599884 , -0.72901107,
        1.7599884 ])

In [76]:
np.dot(transformations.Rz(np.radians(-45)),(target[:3]-home[:3]))

array([ -9.71445147e-17,   2.14103628e-01,   1.96702474e-01])

In [5]:
mylist = [1,2,3]
while mylist:
    print mylist
    print mylist.pop(0)

[1, 2, 3]
1
[2, 3]
2
[3]
3


In [21]:
0.17*sin(45)

0.14465359917080015

In [24]:
((0.17**2)*2)**(1/2.)

0.2404163056034262